#!/usr/bin/env python3
"""Add comprehensive bugfix prompts to prompts.json."""
import json

with open("prompts.json", "r", encoding="utf-8") as f:
    data = json.load(f)

prompts = data["prompts"]
pid = max(int(p["id"]) for p in prompts) + 1

def add(name, content):
    global pid
    prompts.append({"id": str(pid), "name": name, "category": "bugfix", "content": content})
    pid += 1

# ===== SECURITY BUGS =====
add("Fix XSS Vulnerability", "My application is vulnerable to Cross-Site Scripting (XSS):\n\nVulnerable code:\n[code snippet]\n\nUser input is rendered directly in the DOM without sanitization.\n\nFix by:\n1. Escape all user-generated content before rendering\n2. Use framework's built-in escaping (React JSX, Vue {{ }})\n3. Sanitize HTML if rich text is needed (DOMPurify)\n4. Set Content-Security-Policy headers\n5. Use textContent instead of innerHTML\n6. Validate and sanitize on both client and server\n7. Enable HttpOnly flag on cookies to prevent theft")

add("Fix SQL Injection", "My application is vulnerable to SQL injection:\n\nVulnerable code:\n[code snippet]\n\nUser input is concatenated directly into SQL queries.\n\nFix by:\n1. Use parameterized queries / prepared statements\n2. Use ORM methods instead of raw SQL\n3. Validate and whitelist input types\n4. Escape special characters if raw SQL is unavoidable\n5. Apply principle of least privilege to DB user\n6. Enable SQL query logging to detect attacks\n7. Test with common injection payloads: ' OR 1=1 --, UNION SELECT, etc.")

add("Fix CSRF Vulnerability", "My form submissions are vulnerable to Cross-Site Request Forgery:\n\nCurrent form:\n[code snippet]\n\nFix by:\n1. Generate CSRF token per session/request\n2. Include token as hidden field in forms\n3. Validate token on server for all state-changing requests\n4. Use SameSite=Lax or Strict on session cookies\n5. Check Origin/Referer headers as additional defense\n6. Framework-specific: enable CSRF middleware ([framework])\n7. For APIs: use Authorization header instead of cookies")

add("Fix Insecure Direct Object Reference", "Users can access other users' data by changing the ID in the URL:\n\nVulnerable code:\n[code snippet]\n\nGET /api/users/123/documents/456 - any authenticated user can access any document.\n\nFix by:\n1. Verify resource ownership in every handler\n2. Add authorization middleware checking user_id matches\n3. Use indirect references (UUID instead of sequential IDs)\n4. Filter queries by authenticated user's ID\n5. Return 404 (not 403) to avoid information leakage\n6. Add integration tests for authorization boundaries")

add("Fix Sensitive Data Exposure in Logs", "Sensitive data (passwords, tokens, PII) appears in application logs:\n\nLog output:\n[example log with sensitive data]\n\nFix by:\n1. Create a log sanitizer that redacts sensitive fields\n2. Mask patterns: credit card (****1234), email (j***@example.com)\n3. Never log request bodies containing passwords\n4. Redact Authorization headers in request logs\n5. Configure log levels: DEBUG in dev only, INFO+ in production\n6. Audit existing logs for sensitive data\n7. Use structured logging with field-level redaction")

add("Fix Insecure Password Storage", "Passwords are stored in plain text or with weak hashing:\n\nCurrent code:\n[code snippet]\n\nFix by:\n1. Use bcrypt with cost factor 12+ (or argon2id)\n2. Never store plain text passwords\n3. Never use MD5/SHA1/SHA256 alone for passwords\n4. Migrate existing users: rehash on next login\n5. Add password complexity requirements\n6. Implement account lockout after failed attempts\n7. Salt is automatically handled by bcrypt (don't add separate salt)")

add("Fix Open Redirect Vulnerability", "Application redirects users to arbitrary URLs after login:\n\nVulnerable code:\n[code snippet]\n\n/login?redirect=https://evil-site.com works without validation.\n\nFix by:\n1. Whitelist allowed redirect domains\n2. Only allow relative paths for redirects\n3. Validate URL starts with / and not //\n4. Strip protocol from redirect parameter\n5. Use a redirect URL allowlist\n6. Default to homepage if redirect is invalid\n7. Log suspicious redirect attempts")

add("Fix JWT Secret Key Weakness", "JWT tokens can be forged because the secret is weak or exposed:\n\nCurrent code:\n[code snippet]\n\nFix by:\n1. Use a strong random secret (min 256 bits)\n2. Use RS256 (asymmetric) instead of HS256 for distributed systems\n3. Store secret in environment variable, never in code\n4. Rotate secrets periodically with key ID (kid) header\n5. Validate algorithm in verification (prevent 'none' algorithm attack)\n6. Set reasonable expiration times\n7. Implement token revocation/blacklist")

add("Fix Path Traversal Vulnerability", "File download endpoint allows accessing files outside intended directory:\n\nVulnerable code:\n[code snippet]\n\n/api/files?name=../../etc/passwd works.\n\nFix by:\n1. Resolve absolute path and verify it's within allowed directory\n2. Use path.resolve() and check startsWith(allowedDir)\n3. Strip ../ and ..\\\\ from input\n4. Use a whitelist of allowed filenames\n5. Map user input to internal file IDs (indirect reference)\n6. Run application with minimal filesystem permissions\n7. Chroot or containerize the application")

add("Fix Rate Limit Bypass", "Rate limiting can be bypassed using multiple techniques:\n\nCurrent implementation:\n[code snippet]\n\nBypass methods found: [describe]\n\nFix by:\n1. Rate limit by user ID (not just IP) for authenticated users\n2. Include X-Forwarded-For header handling behind proxy\n3. Rate limit by API key for API consumers\n4. Use sliding window algorithm instead of fixed window\n5. Apply rate limits at multiple layers (API gateway + application)\n6. Add CAPTCHA after repeated failures\n7. Monitor and alert on rate limit violations")

# ===== PERFORMANCE BUGS =====
add("Fix Excessive DOM Re-renders", "React component re-renders hundreds of times causing UI lag:\n\nComponent:\n[code snippet]\n\nDiagnose with React DevTools Profiler, then fix:\n1. Identify unnecessary renders (parent state changes)\n2. Wrap with React.memo for pure components\n3. Memoize callbacks with useCallback\n4. Memoize expensive computations with useMemo\n5. Move state down to the component that needs it\n6. Split large components into smaller ones\n7. Use React.lazy for heavy child components\n8. Avoid creating new objects/arrays in render")

add("Fix Main Thread Blocking", "The UI freezes during a heavy computation:\n\n[code snippet]\n\nThe operation takes [X]ms and blocks user interaction.\n\nFix by:\n1. Move heavy computation to Web Worker\n2. Break into smaller chunks with requestIdleCallback\n3. Use setTimeout(0) to yield to browser between chunks\n4. Show progress indicator during processing\n5. Virtualize large list rendering\n6. Debounce expensive event handlers\n7. Use requestAnimationFrame for visual computations\n8. Consider WASM for CPU-intensive tasks")

add("Fix Layout Thrashing", "JavaScript reads then writes DOM properties in a loop causing layout thrashing:\n\n[code snippet]\n\nEach read forces a layout recalculation after the previous write.\n\nFix by:\n1. Batch all DOM reads together, then all writes\n2. Use requestAnimationFrame for DOM writes\n3. Cache DOM measurements in variables\n4. Use transform/opacity for animations (compositor-only)\n5. Use will-change for elements that animate\n6. Use DocumentFragment for batch DOM insertions\n7. Use CSS containment (contain: layout) to limit recalculations")

add("Fix Slow Application Startup", "Application takes [X] seconds to start/load:\n\nCurrent load time: [measurement]\n\nDiagnose and fix:\n1. Analyze bundle with webpack-bundle-analyzer\n2. Code-split routes with dynamic import()\n3. Lazy load heavy libraries (chart, editor, map)\n4. Defer non-critical JavaScript with async/defer\n5. Preload critical resources with <link rel='preload'>\n6. Optimize images (WebP, srcset, lazy loading)\n7. Enable gzip/brotli compression\n8. Use CDN for static assets\n9. Remove unused CSS with PurgeCSS\n10. Minimize render-blocking resources")

add("Fix Cumulative Layout Shift (CLS)", "Page elements shift around during loading, causing poor user experience:\n\nAffected elements: [describe]\n\nFix by:\n1. Set explicit width/height on images and videos\n2. Use aspect-ratio CSS property for media containers\n3. Reserve space for ads and embeds\n4. Avoid inserting content above existing content\n5. Use font-display: swap with size-adjusted fallback font\n6. Preload web fonts\n7. Use min-height on dynamic content areas\n8. Avoid late-loading CSS that changes layout\n9. Target CLS score < 0.1")

add("Fix Largest Contentful Paint (LCP)", "The main content takes too long to appear (LCP > 2.5s):\n\nCurrent LCP: [measurement]\nLCP element: [element]\n\nFix by:\n1. Preload the LCP image/resource\n2. Optimize LCP image size and format (WebP, AVIF)\n3. Remove render-blocking CSS and JS\n4. Use server-side rendering for critical content\n5. Inline critical CSS\n6. Reduce server response time (TTFB)\n7. Use CDN for faster delivery\n8. Avoid lazy-loading the LCP element\n9. Prefetch critical resources")

add("Fix JavaScript Heap Out of Memory", "Node.js process crashes with 'JavaScript heap out of memory':\n\nError: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n\nContext:\n[code snippet]\n\nFix by:\n1. Profile memory with --inspect and Chrome DevTools\n2. Find and fix memory leaks (unreleased references)\n3. Stream large files instead of loading into memory\n4. Process large datasets in chunks/batches\n5. Use Buffer pools for binary data\n6. Increase heap with --max-old-space-size as temporary fix\n7. Implement pagination for database queries\n8. Use WeakMap/WeakRef for caches\n9. Force garbage collection in critical paths (--expose-gc)")

add("Fix API Response Time Degradation", "API responses are getting progressively slower over time:\n\nInitial response time: [X]ms\nCurrent response time: [Y]ms\n\nDiagnose:\n1. Check database query performance (EXPLAIN ANALYZE)\n2. Monitor connection pool utilization\n3. Check for memory leaks growing over time\n4. Review cache hit rates\n5. Check for accumulating data without pagination\n6. Monitor background job queue depth\n7. Check for file descriptor leaks\n8. Review log file sizes and rotation\n9. Restart process and compare to confirm gradual degradation")

# ===== DATABASE BUGS =====
add("Fix Connection Pool Exhaustion", "Application intermittently fails with 'too many connections' or connection timeout:\n\nError: [error message]\nDatabase: [database]\n\nFix by:\n1. Set appropriate pool size (min: 5, max: 20 for most apps)\n2. Ensure connections are returned to pool after use (try/finally)\n3. Set idle connection timeout (30s)\n4. Set connection max lifetime (1 hour)\n5. Add connection validation query (SELECT 1)\n6. Close connections in error handlers\n7. Monitor active/idle connection counts\n8. Use separate pools for long-running queries\n9. Check for connection leaks (connections not released)")

add("Fix Database Query Timeout", "Long-running queries cause request timeouts:\n\nQuery:\n[SQL query]\n\nExecution time: [X] seconds\n\nFix by:\n1. Add appropriate indexes (EXPLAIN to verify)\n2. Set statement_timeout at database level\n3. Add query timeout in application config\n4. Optimize query: rewrite subqueries as JOINs\n5. Add pagination (LIMIT/OFFSET or cursor)\n6. Consider materialized views for complex aggregations\n7. Move heavy queries to background jobs\n8. Implement read replicas for analytics queries\n9. Cache frequently executed expensive queries")

add("Fix Data Type Mismatch in Database", "Queries fail or return wrong results due to data type mismatch:\n\nError: [error message]\nSchema: [relevant columns and types]\nQuery: [query]\n\nFix by:\n1. Align application types with database column types\n2. Use explicit type casting in queries (CAST/::type)\n3. Fix ORM model definitions to match schema\n4. Handle NULL vs empty string differences\n5. Fix date/timestamp type handling\n6. Fix decimal precision for financial data\n7. Add migration to correct column types if needed\n8. Add validation layer before database writes")

add("Fix Duplicate Records in Database", "Duplicate records are created due to missing unique constraints or race conditions:\n\nTable: [table name]\nDuplicate scenario: [describe]\n\nFix by:\n1. Add unique constraint/index on appropriate columns\n2. Use INSERT ... ON CONFLICT (upsert) for idempotency\n3. Use database-level locking for critical sections\n4. Implement optimistic locking with version column\n5. Add application-level deduplication check\n6. Clean up existing duplicates with migration\n7. Use idempotency keys for API endpoints\n8. Add database triggers for complex uniqueness rules")

add("Fix Foreign Key Constraint Violation", "Delete or update operations fail with foreign key constraint errors:\n\nError: [error message]\nTable relationship: [describe]\n\nFix by:\n1. Check dependent records before delete\n2. Implement cascade delete for owned relationships\n3. Set null on delete for optional relationships\n4. Soft delete parent records instead of hard delete\n5. Delete child records first in correct order\n6. Use database transactions for multi-table operations\n7. Return meaningful error message to user\n8. Add UI confirmation showing affected related records")

add("Fix Database Character Set Issues", "Special characters (emojis, CJK, accents) cause errors or display as ???:\n\nDatabase: [database]\nError: [error message or behavior]\n\nFix by:\n1. Set database charset to utf8mb4 (MySQL) or UTF8 (PostgreSQL)\n2. Set collation to utf8mb4_unicode_ci\n3. Update connection string with charset parameter\n4. Alter existing columns: ALTER TABLE ... CONVERT TO CHARACTER SET utf8mb4\n5. Verify application sends Content-Type: charset=utf-8\n6. Check ORM connection encoding settings\n7. Test with emoji, CJK, and accented characters")

add("Fix Optimistic Locking Conflict", "Concurrent edits overwrite each other (last-write-wins problem):\n\nScenario: User A and B edit same record, B's changes overwrite A's.\n\nCode:\n[code snippet]\n\nFix by:\n1. Add version/updated_at column to table\n2. Include version in WHERE clause on update\n3. Return 409 Conflict if version mismatch\n4. Show conflict UI: 'This record was modified by another user'\n5. Offer merge/overwrite/discard options\n6. Auto-refresh data before edit form opens\n7. Consider real-time collaborative editing for frequent conflicts")

# ===== MOBILE / RESPONSIVE BUGS =====
add("Fix Mobile Viewport Issues", "Page doesn't fit mobile screen or has horizontal scrollbar on mobile:\n\nCSS:\n[code snippet]\n\nFix by:\n1. Ensure <meta name='viewport' content='width=device-width, initial-scale=1'>\n2. Replace fixed widths with max-width or relative units\n3. Use overflow-x: hidden on body (temporary diagnosis)\n4. Find overflowing elements: *, *::before, *::after { outline: 1px solid red }\n5. Fix tables with overflow-x: auto wrapper\n6. Use word-break: break-word for long strings\n7. Test with Chrome DevTools device toolbar\n8. Check for elements wider than 100vw")

add("Fix Mobile Keyboard Overlaying Input", "On mobile, the virtual keyboard covers the focused input field:\n\nPlatform: [iOS/Android]\nFramework: [framework]\n\nFix by:\n1. Use visualViewport API to detect keyboard height\n2. Scroll focused element into view: element.scrollIntoView({ block: 'center' })\n3. Add padding-bottom to form when keyboard is open\n4. Use position: sticky on form actions (not position: fixed)\n5. On iOS: use env(safe-area-inset-bottom)\n6. Avoid fixed bottom bars that fight with keyboard\n7. Test with both iOS and Android keyboards")

add("Fix iOS Safe Area Inset", "Content is cut off by the notch or home indicator on iPhone:\n\nCSS:\n[code snippet]\n\nFix by:\n1. Add meta tag: <meta name='viewport' content='viewport-fit=cover'>\n2. Use env(safe-area-inset-top/bottom/left/right)\n3. Apply padding: padding-top: env(safe-area-inset-top);\n4. Fixed bottom bars: padding-bottom: calc(16px + env(safe-area-inset-bottom))\n5. Use @supports (padding: env(safe-area-inset-top)) for fallback\n6. Test on iPhone X+ and iPad with rounded corners\n7. Landscape mode needs left/right insets too")

add("Fix Mobile Orientation Change Bug", "Layout breaks or state is lost when rotating device:\n\n[describe the issue]\n\nFix by:\n1. Listen to orientationchange or resize event\n2. Use CSS media queries: (orientation: portrait/landscape)\n3. Recalculate dynamic dimensions on resize\n4. Debounce resize handler (250ms)\n5. Save and restore scroll position\n6. Test both portrait-to-landscape and landscape-to-portrait\n7. Use viewport units (vw, vh, dvh) carefully\n8. Consider using dvh (dynamic viewport height) instead of vh")

add("Fix Touch Scroll Interference", "Scrollable element inside a page blocks page scroll or vice versa:\n\nScenario: [describe - e.g., modal with scroll, map, carousel]\n\nFix by:\n1. Use overscroll-behavior: contain on scrollable child\n2. Prevent body scroll when modal is open: body { overflow: hidden }\n3. Use touch-action CSS property to control gesture handling\n4. For modals: save/restore body scroll position\n5. For carousels: detect swipe direction before preventing default\n6. Use passive: true for scroll event listeners\n7. Test on real devices (iOS Safari behaves differently)")

add("Fix 100vh Mobile Browser Issue", "100vh is taller than the visible viewport on mobile because of the browser UI bar:\n\nCSS:\n[code snippet]\n\nFix by:\n1. Use 100dvh (dynamic viewport height) instead of 100vh\n2. Fallback: min-height: 100vh; min-height: -webkit-fill-available;\n3. Use CSS custom property set by JS: --vh = window.innerHeight * 0.01\n4. Apply: height: calc(var(--vh, 1vh) * 100)\n5. Update on resize/orientationchange\n6. For fixed bottom elements: use env(safe-area-inset-bottom)\n7. Test on iOS Safari and Chrome Android")

add("Fix iOS Rubber Band Scroll", "Unwanted rubber-band/bounce scroll effect on iOS web app:\n\nContext: [describe - full page app, modal, etc.]\n\nFix by:\n1. Add overscroll-behavior: none to html/body\n2. Use position: fixed on body when modal is open\n3. For web apps: set overflow: hidden on root element\n4. Allow scroll on specific scrollable areas only\n5. Prevent touchmove on non-scrollable areas\n6. Use -webkit-overflow-scrolling: touch for smooth scroll in scrollable areas\n7. Note: cannot fully disable in Safari without trade-offs")

# ===== ACCESSIBILITY BUGS =====
add("Fix Focus Trap Not Working", "Tab key escapes modal/dialog and focuses elements behind the overlay:\n\nModal code:\n[code snippet]\n\nFix by:\n1. Collect all focusable elements inside modal\n2. On Tab at last element: focus first element\n3. On Shift+Tab at first element: focus last element\n4. Set focus to first focusable element on open\n5. Return focus to trigger element on close\n6. Add aria-modal='true' and role='dialog'\n7. Use inert attribute on background content\n8. Or use <dialog> element with showModal() for native trap")

add("Fix Screen Reader Not Announcing Changes", "Dynamic content updates are not announced by screen readers:\n\n[code snippet]\n\nFix by:\n1. Add aria-live='polite' to the container of dynamic content\n2. Use aria-live='assertive' for urgent messages (errors)\n3. Add role='alert' for error messages\n4. Add role='status' for status updates\n5. Ensure the live region exists in DOM before content changes\n6. Don't use aria-live on elements that change too frequently\n7. Test with VoiceOver (Mac), NVDA (Windows), TalkBack (Android)\n8. Use aria-atomic='true' to announce full region content")

add("Fix Color Contrast Insufficient", "Text fails WCAG 2.1 AA color contrast requirements (min 4.5:1 for normal text):\n\nAffected elements:\n[describe colors/elements]\n\nFix by:\n1. Check contrast ratio with browser DevTools accessibility panel\n2. Normal text: minimum 4.5:1 contrast ratio\n3. Large text (18px+ or 14px+ bold): minimum 3:1\n4. Use accessible color palette generator\n5. Test with color blindness simulators\n6. Avoid conveying meaning through color alone (add icons/text)\n7. Ensure focus indicators have sufficient contrast\n8. Dark mode: verify contrast for both themes")

add("Fix Missing Form Labels", "Form inputs have no associated labels, making them inaccessible:\n\n[code snippet]\n\nFix by:\n1. Add <label for='inputId'> for every input\n2. Ensure id on input matches for on label\n3. For visual-only designs: use sr-only class for hidden label\n4. Or use aria-label on input directly\n5. Add aria-describedby for helper text\n6. Add aria-required='true' for required fields\n7. Group related inputs with <fieldset> and <legend>\n8. Placeholder is NOT a substitute for label")

add("Fix Keyboard Trap", "User gets stuck in a component and cannot Tab out:\n\nComponent:\n[code snippet]\n\nFix by:\n1. Ensure Tab and Shift+Tab can exit the component\n2. Exception: modals should trap focus (but Escape should close)\n3. Check for tabindex values preventing natural tab order\n4. Avoid tabindex > 0 (breaks natural order)\n5. Test keyboard-only navigation through entire page\n6. Ensure custom widgets (dropdown, calendar) allow Tab to exit\n7. Add Escape key handler to dismiss overlays\n8. Use roving tabindex for widget internal navigation")

# ===== I18N BUGS =====
add("Fix RTL Layout Breaking", "Page layout breaks in RTL (right-to-left) languages like Arabic or Hebrew:\n\nCSS:\n[code snippet]\n\nFix by:\n1. Use dir='rtl' on html element for RTL languages\n2. Replace margin-left/right with margin-inline-start/end\n3. Replace padding-left/right with padding-inline-start/end\n4. Use logical properties: inset-inline-start instead of left\n5. Flip icons that indicate direction (arrows, but not checkmarks)\n6. Use text-align: start instead of left\n7. Mirror horizontal layouts with CSS logical properties\n8. Test with actual RTL text, not just dir attribute")

add("Fix Number and Currency Formatting", "Numbers display incorrectly for different locales (1,000 vs 1.000):\n\nCurrent code:\n[code snippet]\n\nFix by:\n1. Use Intl.NumberFormat for number display\n2. Use Intl.NumberFormat with style:'currency' for money\n3. Never hardcode decimal/thousand separators\n4. Format dates with Intl.DateTimeFormat\n5. Store numbers as integers (cents for money)\n6. Pass locale from user preferences or browser\n7. Test with locales: en-US, de-DE, ja-JP, ar-SA\n8. Handle number input: accept both , and . as decimal separator")

add("Fix Pluralization in Translations", "Translations show wrong plural forms ('1 items' or 'You have 0 message'):\n\nCurrent code:\n[code snippet]\n\nFix by:\n1. Use i18n library's plural rules (not simple if/else)\n2. English: one/other. But some languages have: zero/one/two/few/many/other\n3. ICU MessageFormat syntax: {count, plural, one {# item} other {# items}}\n4. Test with 0, 1, 2, 5, 21 (different plural categories)\n5. Never concatenate translated strings\n6. Include count placeholder in translation key\n7. Some languages: Russian (1 item, 2-4 itema, 5-20 items)")

add("Fix Truncated Translated Text", "Translated text overflows containers because translations are longer than English:\n\n[describe affected UI elements]\n\nFix by:\n1. Design with 30-40% extra space for translations\n2. Use flexible layouts (flexbox/grid) not fixed widths\n3. Allow text wrapping in buttons and labels\n4. Use text-overflow: ellipsis with title attribute for tooltips\n5. Test with longest translations (German, Finnish are ~30% longer)\n6. Consider using pseudo-localization during development\n7. Set min-width rather than fixed width on text containers")

# ===== NODE.JS SPECIFIC BUGS =====
add("Fix Event Loop Blocking in Node.js", "Node.js server becomes unresponsive during CPU-intensive operation:\n\nCode:\n[code snippet]\n\nAll other requests hang while this operation runs.\n\nFix by:\n1. Move CPU-intensive work to worker_threads\n2. Use child_process.fork for isolated processing\n3. Break operation into async chunks with setImmediate()\n4. Use streaming for large file processing\n5. Implement job queue (Bull/BullMQ) for background work\n6. Monitor event loop lag with perf_hooks\n7. Set up health check that detects blocked event loop\n8. Consider microservice for CPU-heavy tasks")

add("Fix Node.js Stream Error Handling", "Streams fail silently or crash without proper error handling:\n\nCode:\n[code snippet]\n\nFix by:\n1. Always handle 'error' event on every stream\n2. Use pipeline() instead of pipe() for automatic error propagation\n3. Handle 'error' on both readable and writable streams\n4. Implement stream.destroy() in error handlers\n5. Use try/catch with async iterators (for await...of)\n6. Handle backpressure (check write() return value)\n7. Clean up resources in 'close' event\n8. Set timeout for idle streams")

add("Fix Node.js Process Crash on Unhandled Error", "Node.js process crashes unexpectedly in production:\n\nError from logs:\n[error message]\n\nFix by:\n1. Add process.on('uncaughtException') handler - log and exit gracefully\n2. Add process.on('unhandledRejection') handler\n3. Wrap all async route handlers with error-catching middleware\n4. Never ignore promise rejections\n5. Use process manager (PM2, nodemon) for auto-restart\n6. Implement graceful shutdown: close server, drain connections, cleanup\n7. Add health check endpoint\n8. Set up error monitoring (Sentry, Datadog)")

add("Fix Node.js File Descriptor Leak", "Application hits EMFILE (too many open files) after running for a while:\n\nError: EMFILE: too many open files\n\nFix by:\n1. Ensure all opened files/streams are closed in finally blocks\n2. Use graceful-fs for automatic retry on EMFILE\n3. Check for unclosed database connections\n4. Verify HTTP keep-alive connections are being recycled\n5. Increase file descriptor limit: ulimit -n 65536\n6. Monitor open file descriptors: lsof -p <pid> | wc -l\n7. Use connection pooling for database and HTTP clients")

# ===== REACT SPECIFIC BUGS =====
add("Fix React Context Re-render Performance", "All consumers re-render when any context value changes:\n\n[code snippet]\n\nFix by:\n1. Split large context into multiple smaller contexts\n2. Memoize context value with useMemo\n3. Separate frequently-changing values from stable ones\n4. Use useReducer instead of multiple useState in context\n5. Consider state management library for complex state\n6. Wrap consumers with React.memo\n7. Use context selector pattern (use-context-selector library)\n8. Move non-state helpers out of context")

add("Fix React Suspense Error Boundary", "Component wrapped in Suspense crashes instead of showing fallback:\n\n[code snippet]\n\nError: [error message]\n\nFix by:\n1. Wrap Suspense with ErrorBoundary for error cases\n2. ErrorBoundary catches render errors, Suspense handles loading\n3. Ensure lazy component returns default export\n4. Add retry logic in ErrorBoundary fallback\n5. Check that the promise thrown by Suspense is valid\n6. For data fetching: use libraries that support Suspense (React Query, SWR)\n7. Nest error boundary inside Suspense for granular error handling")

add("Fix React useEffect Dependency Warning", "React warns about missing dependencies in useEffect:\n\nWarning: React Hook useEffect has a missing dependency: '[dep]'\n\n[code snippet]\n\nFix properly (NOT by disabling the rule):\n1. Add the dependency if it should trigger re-run\n2. Move the function inside useEffect if it's only used there\n3. Wrap function with useCallback if it's a prop or used elsewhere\n4. Use useRef for values that shouldn't trigger re-run\n5. Use functional state update: setCount(c => c + 1) instead of count\n6. Move static values outside component\n7. Split effect into multiple effects with different dependencies")

add("Fix React Prop Drilling Problem", "Props are passed through 5+ levels of components that don't use them:\n\n[describe component hierarchy]\n\nFix by:\n1. Use React Context for widely-shared state\n2. Use component composition (pass components as props)\n3. Use render props pattern\n4. Restructure: move state closer to where it's used\n5. Use custom hooks to encapsulate shared logic\n6. Consider state management (Zustand, Jotai) for complex cases\n7. Apply 'lifting state up' or 'pushing state down' as appropriate")

add("Fix React Memory Leak on Unmount", "Warning: Can't perform a React state update on an unmounted component.\n\n[code snippet]\n\nFix by:\n1. Return cleanup function from useEffect\n2. Use AbortController for fetch requests: abort on unmount\n3. Clear timeouts/intervals in cleanup\n4. Unsubscribe from WebSocket/event listeners\n5. Cancel async operations: use mounted ref flag\n6. Use React Query or SWR which handle this automatically\n7. For class components: check this._isMounted before setState")

# ===== NEXT.JS SPECIFIC BUGS =====
add("Fix Next.js API Route Not Working", "Next.js API route returns 404 or wrong response:\n\nFile: pages/api/[route].js or app/api/[route]/route.js\n\n[code snippet]\n\nFix by:\n1. Check file path matches expected URL pattern\n2. App Router: export named functions (GET, POST), not default\n3. Pages Router: export default function handler(req, res)\n4. Verify request method matching\n5. Check for conflicting routes (static vs dynamic)\n6. Ensure proper Response/NextResponse format\n7. Check middleware is not blocking the route\n8. Restart dev server after adding new API routes")

add("Fix Next.js Server Component Error", "Component works locally but fails in production with server/client mismatch:\n\nError: [error message]\n\nFix by:\n1. Add 'use client' directive for components using hooks/state/effects\n2. Server Components: no useState, useEffect, event handlers\n3. Don't import client components into server component modules\n4. Use dynamic imports with ssr: false for browser-only libraries\n5. Check for window/document usage in server components\n6. Separate server and client logic into different files\n7. Use suspense boundaries at server/client boundaries")

add("Fix Next.js Image Optimization Issues", "Next.js Image component shows errors or doesn't optimize:\n\nError: [error message]\n\n[code snippet]\n\nFix by:\n1. Configure remotePatterns in next.config.js for external images\n2. Provide width and height props (or use fill with parent sizing)\n3. For fill layout: parent must have position: relative and dimensions\n4. Check sharp is installed for production image optimization\n5. Set proper sizes attribute for responsive images\n6. Configure loader for custom CDN\n7. Use priority={true} for above-the-fold images\n8. Increase imageSizeLimit if seeing size warnings")

# ===== CSS SPECIFIC BUGS =====
add("Fix CSS Specificity War", "CSS styles not applying because they're overridden by higher specificity:\n\n[code snippet]\n\nFix by:\n1. Use browser DevTools to see which rule wins\n2. Increase specificity strategically (add parent selector)\n3. Avoid !important (last resort only)\n4. Use BEM naming convention to keep specificity flat\n5. Order stylesheets correctly (custom after framework)\n6. Use CSS layers (@layer) for explicit precedence\n7. Use :where() to reduce specificity of utility selectors\n8. Refactor to use CSS custom properties for overrides")

add("Fix CSS Animation Jank", "CSS animation stutters and drops frames:\n\n[code snippet]\n\nFix by:\n1. Only animate transform and opacity (compositor-only properties)\n2. Never animate width, height, top, left, margin, padding\n3. Use transform: translateX() instead of left\n4. Add will-change: transform on elements before animation\n5. Use contain: layout style to limit reflow scope\n6. Reduce animation complexity (fewer DOM elements)\n7. Test with Chrome DevTools Performance panel\n8. Use requestAnimationFrame for JS-driven animations\n9. Avoid animating elements that cause paint (box-shadow, border-radius)")

add("Fix CSS Position Sticky Not Working", "position: sticky has no effect - element scrolls normally:\n\nCSS:\n[code snippet]\n\nHTML structure:\n[code snippet]\n\nFix by:\n1. Ensure top/bottom value is set (top: 0)\n2. Check parent doesn't have overflow: hidden/auto/scroll\n3. Check all ancestors for overflow property\n4. Parent must have enough height for sticky to be meaningful\n5. Remove any transform on ancestors (creates new stacking context)\n6. Check element isn't inside a flex/grid item with overflow\n7. Test: add background color to verify element position\n8. Use position: -webkit-sticky for older Safari")

add("Fix CSS Media Query Conflicts", "Styles from different media queries overlap or conflict:\n\n[code snippet]\n\nFix by:\n1. Use consistent breakpoint approach (mobile-first or desktop-first)\n2. Mobile-first: min-width queries, styles cascade up\n3. Desktop-first: max-width queries, styles cascade down\n4. Don't mix min-width and max-width without careful overlap check\n5. Define breakpoints as CSS custom properties or Sass variables\n6. Use range syntax: @media (768px <= width < 1024px)\n7. Order media queries from small to large (mobile-first)\n8. Test at exact breakpoint values to catch edge cases")

add("Fix CSS Variable Not Updating", "CSS custom property changes in JavaScript but style doesn't update:\n\n[code snippet]\n\nFix by:\n1. Verify setting on correct element: document.documentElement.style.setProperty('--var', value)\n2. Check for typo in variable name (exact match including --)\n3. Ensure the property using the variable uses var(--name)\n4. Check if a more specific declaration overrides the variable\n5. Verify the variable is defined in scope (not in unrelated selector)\n6. Use getComputedStyle to debug current value\n7. Check for fallback value syntax: var(--name, fallback)")

# ===== THIRD-PARTY INTEGRATION BUGS =====
add("Fix Package Version Conflict", "Two packages require incompatible versions of a shared dependency:\n\nError:\n[error message - e.g., peer dependency conflict]\n\nFix by:\n1. Check exact version requirements: npm ls [package]\n2. Try npm install --legacy-peer-deps as temporary fix\n3. Update both packages to latest compatible versions\n4. Use npm overrides or yarn resolutions to force version\n5. Check if one package has alternative that's compatible\n6. Lock specific version in package.json\n7. Consider using a different package manager (pnpm strict mode)\n8. Report incompatibility to package maintainers")

add("Fix Third-Party API Breaking Change", "Application breaks after third-party API updated their response format:\n\nOld response: [old format]\nNew response: [new format]\n\nFix by:\n1. Add defensive response parsing (optional chaining, defaults)\n2. Create an adapter/mapper layer between API and application\n3. Version-pin API calls if API supports versioning\n4. Add response schema validation\n5. Implement circuit breaker for external API calls\n6. Add monitoring/alerts for response format changes\n7. Cache last known good response as fallback\n8. Write integration tests that verify API contract")

add("Fix OAuth Provider Login Failure", "Social login (Google/GitHub/Apple) suddenly stopped working:\n\nError: [error message]\nProvider: [provider]\n\nDebug checklist:\n1. Check OAuth credentials haven't expired\n2. Verify redirect URI matches exactly (including trailing slash)\n3. Check provider's API status page\n4. Verify scopes haven't been deprecated\n5. Check SSL certificate is valid (some providers require HTTPS)\n6. Review provider's changelog for breaking changes\n7. Check rate limits haven't been exceeded\n8. Verify client secret hasn't been rotated\n9. Test with provider's OAuth playground/debugger")

add("Fix Stripe Webhook Signature Failure", "Stripe webhooks return signature verification errors:\n\nError: Webhook signature verification failed\n\nCode:\n[code snippet]\n\nFix by:\n1. Use raw request body (not parsed JSON) for verification\n2. Check you're using the correct webhook signing secret (not API key)\n3. Each endpoint has its own signing secret in Stripe dashboard\n4. Verify Content-Type is application/json\n5. Don't modify the request body before verification\n6. In Express: use express.raw({type: 'application/json'}) for webhook route\n7. Check system clock is synchronized (signatures are time-sensitive)\n8. Test with Stripe CLI: stripe listen --forward-to localhost")

# ===== TESTING BUGS =====
add("Fix Flaky Test", "Test passes sometimes and fails other times without code changes:\n\nTest:\n[code snippet]\n\nFix by:\n1. Remove dependency on execution order (test isolation)\n2. Mock system time for date-dependent tests\n3. Await all async operations (don't rely on timing)\n4. Use waitFor/findBy instead of getBy for async DOM updates\n5. Clean up global state in afterEach\n6. Fix shared mutable state between tests\n7. Add retry with logging to identify the flaky condition\n8. Use fake timers instead of real timeouts\n9. Ensure database state is reset between tests")

add("Fix Mock Not Working in Tests", "Mock/stub doesn't intercept the real function call:\n\n[code snippet]\n\nFix by:\n1. Verify mock is set up before the code under test runs\n2. Mock the module, not the imported reference (jest.mock at top level)\n3. For named exports: mock the entire module\n4. For default exports: mock with __esModule: true\n5. Check import order - mocks must be hoisted\n6. Use spyOn for method mocking on existing objects\n7. Verify mock path matches actual import path exactly\n8. Reset mocks in afterEach to prevent test leakage")

add("Fix Test Database Pollution", "Tests fail when run together but pass individually:\n\n[describe the test failures]\n\nFix by:\n1. Use transactions that rollback after each test\n2. Truncate tables in beforeEach (order matters for foreign keys)\n3. Use unique test data per test (random IDs/names)\n4. Don't rely on auto-increment IDs in assertions\n5. Isolate test database from development database\n6. Use factory functions for consistent test data creation\n7. Run tests in --runInBand for debugging (sequential)\n8. Check for beforeAll shared state that leaks")

# ===== DEPLOYMENT / DEVOPS BUGS =====
add("Fix Zero-Downtime Deployment Failure", "Application has downtime during deployment:\n\nCurrent deployment process:\n[describe]\n\nFix by:\n1. Run new version alongside old version (blue-green or rolling)\n2. Health check before routing traffic to new version\n3. Graceful shutdown: stop accepting new requests, finish current ones\n4. Database migrations must be backward-compatible\n5. Use readiness probe to delay traffic until app is ready\n6. Implement connection draining (30s timeout)\n7. Feature flags for gradual rollout\n8. Automated rollback on health check failure")

add("Fix Environment Variables Not Loading", "Application fails in deployment because environment variables are missing:\n\nError: [error message]\nMissing variable: [variable name]\n\nFix by:\n1. Verify .env file is not committed but variables are set in platform\n2. Check environment variable names (case-sensitive)\n3. Next.js: NEXT_PUBLIC_ prefix for client-side variables\n4. Vite: VITE_ prefix for client-side variables\n5. Docker: pass via -e flag or env_file\n6. Validate all required env vars on startup with clear error messages\n7. Document all required env vars in README/example.env\n8. Use config validation library (envalid, zod)")

add("Fix DNS Propagation Issue", "New domain/subdomain not resolving after DNS change:\n\nDomain: [domain]\nExpected: [IP/CNAME]\nActual: NXDOMAIN or old IP\n\nFix by:\n1. Verify DNS records are correct: dig [domain] or nslookup\n2. Check TTL on previous record (may need to wait for expiry)\n3. Flush local DNS cache: sudo dscacheutil -flushcache (Mac)\n4. Try different DNS resolver: dig @8.8.8.8 [domain]\n5. Check nameserver delegation is correct\n6. Verify no CAA records blocking SSL certificate\n7. Use DNS propagation checker (whatsmydns.net)\n8. Lower TTL to 300s before future DNS changes")

add("Fix SSL Certificate Error", "Application shows SSL certificate error in browser:\n\nError: [NET::ERR_CERT_* or specific error]\n\nDiagnose and fix:\n1. ERR_CERT_DATE_INVALID: Certificate expired - renew or set up auto-renewal\n2. ERR_CERT_COMMON_NAME_INVALID: Domain doesn't match certificate\n3. ERR_CERT_AUTHORITY_INVALID: Self-signed or untrusted CA\n4. Check certificate chain is complete (include intermediate certs)\n5. Verify SSL config: ssl-config.mozilla.org\n6. Set up Let's Encrypt with auto-renewal (certbot)\n7. For development: add self-signed cert to trusted store\n8. Test with: openssl s_client -connect domain:443")

add("Fix Container Health Check Failing", "Kubernetes/Docker health check fails but application seems to work:\n\nHealth check config:\n[code snippet]\n\nFix by:\n1. Verify health endpoint is accessible from inside container\n2. Check port matches application listening port\n3. Increase initialDelaySeconds for slow-starting apps\n4. Ensure health endpoint doesn't require authentication\n5. Check liveness vs readiness probe configuration\n6. Liveness: is the process alive? (simple check)\n7. Readiness: can it handle traffic? (check dependencies)\n8. Add logging to health endpoint for debugging\n9. Test: kubectl exec into pod and curl health endpoint")

# ===== STATE MANAGEMENT BUGS =====
add("Fix Redux State Mutation", "Redux state is being mutated directly causing bugs:\n\n[code snippet]\n\nSymptoms: component doesn't re-render, time-travel debugging broken.\n\nFix by:\n1. Never mutate state directly: state.items.push(item) is wrong\n2. Use spread operator: { ...state, items: [...state.items, item] }\n3. Use Redux Toolkit (createSlice) which uses Immer internally\n4. Enable Redux DevTools to catch mutations\n5. Use Immer's produce() for complex nested updates\n6. Add redux-immutable-state-invariant middleware in development\n7. Deep clone if needed: structuredClone(state)")

add("Fix Zustand Store Not Updating UI", "Zustand store state changes but component doesn't re-render:\n\n[code snippet]\n\nFix by:\n1. Use selector to subscribe to specific state: useStore(s => s.field)\n2. Don't subscribe to entire store: useStore() triggers on any change\n3. For objects/arrays: use shallow comparison: useStore(s => s.items, shallow)\n4. Ensure set() creates new object reference, not mutation\n5. Don't derive state in component - use store selectors\n6. Check if component is mounted (React StrictMode double-render)\n7. Use devtools middleware to debug state changes")

add("Fix Local Storage Sync Issue", "State saved to localStorage becomes out of sync with application state:\n\n[code snippet]\n\nFix by:\n1. Use single source of truth (either state or localStorage, not both)\n2. Initialize state from localStorage on app load\n3. Write to localStorage in useEffect when state changes\n4. Handle JSON parse errors (corrupted data)\n5. Add schema version for migration when structure changes\n6. Listen to 'storage' event for cross-tab sync\n7. Debounce localStorage writes for frequently changing state\n8. Clear stale data with version check")

# ===== MISCELLANEOUS COMMON BUGS =====
add("Fix Regex Catastrophic Backtracking", "Regex pattern causes the application to hang on certain inputs:\n\nPattern: [regex]\nInput that hangs: [input]\n\nFix by:\n1. Avoid nested quantifiers: (a+)+ or (a*)*\n2. Use atomic groups or possessive quantifiers if supported\n3. Make patterns more specific (character classes instead of .)\n4. Add input length limit before regex match\n5. Use regex timeout (RE2 library for guaranteed linear time)\n6. Test with ReDoS detection tools\n7. Consider using simpler string methods instead of regex\n8. Break complex regex into multiple simpler steps")

add("Fix Floating Point Arithmetic", "Calculations produce incorrect results due to floating point precision:\n\nExample: 0.1 + 0.2 = 0.30000000000000004\n\nCode:\n[code snippet]\n\nFix by:\n1. For money: use integer cents (1000 = $10.00)\n2. Use decimal.js or big.js library for precise math\n3. Use Math.round() only for display, not intermediate calculations\n4. Compare with epsilon: Math.abs(a - b) < Number.EPSILON\n5. Use toFixed() for display formatting only\n6. In SQL: use DECIMAL(10,2) not FLOAT for money\n7. Never compare floats with === directly\n8. Consider using BigInt for large integer calculations")

add("Fix Deep Copy vs Shallow Copy Bug", "Object modifications unexpectedly affect the original:\n\n[code snippet]\n\nSpread operator or Object.assign only shallow copies.\n\nFix by:\n1. Use structuredClone() for deep copy (modern browsers/Node 17+)\n2. Use JSON.parse(JSON.stringify(obj)) for simple objects (no functions/dates)\n3. Use lodash _.cloneDeep() for complex objects\n4. Be aware: spread/Object.assign only copies first level\n5. For arrays of objects: arr.map(item => ({...item}))\n6. For immutable updates: use Immer produce()\n7. Consider using immutable data structures (Immutable.js)")

add("Fix URL Encoding/Decoding Bug", "Special characters in URLs cause routing or API errors:\n\nProblem: [describe - e.g., spaces, unicode, #, & in parameters]\n\nCode:\n[code snippet]\n\nFix by:\n1. Use encodeURIComponent() for query parameter values\n2. Use encodeURI() for full URLs (preserves structural characters)\n3. Don't double-encode (check if already encoded)\n4. Decode on server: decodeURIComponent()\n5. Handle + as space in query strings\n6. Use URLSearchParams API for building query strings\n7. Use URL constructor for URL manipulation\n8. Be careful with # (fragment) in SPAs")

add("Fix JSON Serialization Circular Reference", "JSON.stringify() fails with 'Converting circular structure to JSON':\n\n[code snippet]\n\nObject has circular references (e.g., parent.child.parent).\n\nFix by:\n1. Use replacer function to skip circular references\n2. Use flatted library for circular JSON support\n3. Create a toJSON() method on the object to control serialization\n4. Break circular references before serialization\n5. Use WeakSet to track visited objects in custom serializer\n6. Restructure data to avoid circular references\n7. Use only the fields you need: pick specific properties")

add("Fix Debounce/Throttle Not Working", "Debounced function fires on every call instead of waiting:\n\n[code snippet]\n\nFix by:\n1. Create debounced function ONCE (not on every render)\n2. In React: use useMemo or useRef to persist the debounced function\n3. Wrong: onChange={debounce(fn, 300)} - creates new debounce each render\n4. Right: const debouncedFn = useMemo(() => debounce(fn, 300), [])\n5. Cancel debounce on unmount: debouncedFn.cancel()\n6. For search: debounce input handler, not API call\n7. For resize: throttle (not debounce) for smoother updates")

add("Fix Clipboard Copy Not Working", "navigator.clipboard.writeText() fails or does nothing:\n\n[code snippet]\n\nFix by:\n1. Clipboard API requires HTTPS (or localhost for dev)\n2. Must be triggered by user gesture (click handler)\n3. Handle permission denial gracefully\n4. Fallback for older browsers: document.execCommand('copy')\n5. For fallback: create temporary textarea, select, copy, remove\n6. Check navigator.clipboard is available before using\n7. Handle async: await navigator.clipboard.writeText(text)\n8. Show toast feedback on success/failure")

add("Fix localStorage Quota Exceeded", "Application crashes with QuotaExceededError when saving to localStorage:\n\nError: QuotaExceededError: The quota has been exceeded\n\nFix by:\n1. localStorage limit is ~5-10MB per origin\n2. Wrap setItem in try/catch\n3. Implement storage cleanup: remove old/unused items\n4. Compress data before storing (lz-string library)\n5. Use IndexedDB for larger data (50MB+)\n6. Implement LRU eviction for cached data\n7. Monitor storage usage: navigator.storage.estimate()\n8. Consider server-side storage for large datasets")

add("Fix setTimeout/setInterval Drift", "Timer drifts over time and becomes inaccurate:\n\n[code snippet]\n\nAfter [X] minutes, the timer is off by [Y] seconds.\n\nFix by:\n1. Use absolute timestamps instead of incremental delays\n2. Calculate drift and adjust: nextTick = startTime + interval * count\n3. Use requestAnimationFrame for visual timers\n4. Use Web Workers for timers that must run in background\n5. Use performance.now() for high-precision timing\n6. Background tabs may throttle setTimeout to 1s minimum\n7. For countdowns: compare against target time, don't decrement")

add("Fix Service Worker Cache Stale", "Users see old version of the app despite deploying new code:\n\nService worker config:\n[code snippet]\n\nFix by:\n1. Update service worker cache version on each deploy\n2. Implement cache-first with network update strategy\n3. Use skipWaiting() and clients.claim() for immediate activation\n4. Show 'Update available' prompt to user\n5. Clear old caches in activate event\n6. Add build hash to cache names\n7. Ensure index.html is never cached (or cache with revalidation)\n8. Use workbox for reliable caching strategies")

add("Fix Web Worker Communication Error", "Web Worker throws or doesn't receive messages:\n\nMain thread:\n[code snippet]\n\nWorker:\n[code snippet]\n\nFix by:\n1. Verify worker file path is correct and accessible\n2. Use postMessage for communication (not shared memory by default)\n3. Handle errors: worker.onerror for uncaught exceptions\n4. Structured clone: some objects can't be transferred (DOM, functions)\n5. Use transferable objects for large ArrayBuffers (transfer, not clone)\n6. For Webpack/Vite: use worker-loader or import with ?worker\n7. Terminate workers when no longer needed: worker.terminate()")

add("Fix IndexedDB Transaction Error", "IndexedDB operations fail with transaction errors:\n\nError: [error message]\n\nCode:\n[code snippet]\n\nFix by:\n1. Complete all operations within the same transaction\n2. Don't await non-IDB async operations inside a transaction\n3. Transactions auto-close when idle - keep them busy\n4. Use correct transaction mode: 'readwrite' for mutations\n5. Handle version upgrades properly in onupgradeneeded\n6. Close database connection before deleting/upgrading\n7. Use idb library for promise-based wrapper\n8. Handle QuotaExceededError for storage limits")

add("Fix Print Stylesheet Issues", "Page prints incorrectly: wrong layout, missing content, cut-off elements:\n\nCurrent page:\n[describe layout]\n\nFix by:\n1. Add @media print { } stylesheet\n2. Hide non-essential elements: nav, footer, ads { display: none }\n3. Remove background colors: * { background: white !important }\n4. Ensure text is black: * { color: black !important }\n5. Use page-break-inside: avoid on cards and tables\n6. Expand truncated content (show full text, not ellipsis)\n7. Show URLs after links: a[href]::after { content: ' (' attr(href) ')' }\n8. Set width to auto and remove fixed widths\n9. Test with Chrome DevTools: Rendering > Emulate CSS media type: print")

add("Fix SVG Rendering Inconsistency", "SVG icons/graphics render differently across browsers:\n\n[code snippet]\n\nFix by:\n1. Add viewBox attribute for consistent scaling\n2. Set explicit width and height (or use CSS)\n3. Use currentColor for dynamic fill/stroke coloring\n4. Remove unnecessary XML namespace declarations\n5. Set display: block to remove inline spacing gap\n6. Optimize with SVGO (remove metadata, simplify paths)\n7. For icon systems: use <symbol> and <use> pattern\n8. Test on Safari - often has different SVG rendering")

add("Fix Content Security Policy Blocking Resources", "CSP headers block scripts, styles, or images from loading:\n\nConsole error: Refused to load the script '[url]' because it violates the Content Security Policy directive.\n\nFix by:\n1. Identify which directive is blocking: script-src, style-src, img-src, etc.\n2. Add the source to the appropriate directive\n3. Use nonce-based CSP for inline scripts: script-src 'nonce-abc123'\n4. Avoid 'unsafe-inline' and 'unsafe-eval' if possible\n5. Use report-uri to collect violations without blocking\n6. Start with Content-Security-Policy-Report-Only header\n7. Gradually tighten policy\n8. Test all pages after CSP changes")

add("Fix WebGL/Canvas Rendering Issue", "Canvas or WebGL content doesn't render or shows black screen:\n\n[code snippet]\n\nFix by:\n1. Check WebGL context creation: gl = canvas.getContext('webgl2') || canvas.getContext('webgl')\n2. Check for context lost event and handle restoration\n3. Verify canvas has explicit width/height attributes (not just CSS)\n4. Check for GPU acceleration disabled in browser\n5. Set preserveDrawingBuffer: true if capturing screenshots\n6. Handle high-DPI displays: canvas.width = canvas.clientWidth * devicePixelRatio\n7. Check for maximum texture size limits\n8. Verify shaders compile without errors: gl.getShaderInfoLog()")

add("Fix PDF Generation Encoding Issue", "Generated PDF shows garbled text or missing characters:\n\nLibrary: [pdfkit/puppeteer/jspdf]\n\nFix by:\n1. Embed fonts that support required characters\n2. Use Unicode-compatible fonts (Noto Sans supports most languages)\n3. Set proper encoding in PDF metadata\n4. For Puppeteer: ensure page is fully loaded before PDF generation\n5. Check font file is accessible at build/runtime\n6. For CJK characters: use CJK-specific font subset\n7. Test with various character sets: Latin, CJK, Arabic, Emoji")

add("Fix WebSocket Memory Leak", "WebSocket connections accumulate and memory grows:\n\n[code snippet]\n\nFix by:\n1. Track all active connections in a Set/Map\n2. Remove connection from tracking on close/error\n3. Implement heartbeat to detect dead connections\n4. Close idle connections after timeout (5 minutes)\n5. Set maximum connections per user\n6. Handle 'close' event for cleanup\n7. Properly destroy socket on server shutdown\n8. Monitor connection count metrics\n9. Use WeakRef for connection metadata if possible")

add("Fix Cron Job Running Multiple Times", "Scheduled job runs multiple times simultaneously in scaled environment:\n\nCurrent setup:\n[code snippet]\n\nFix by:\n1. Use distributed lock (Redis SETNX with TTL)\n2. Use database advisory locks\n3. Designate single instance for cron (leader election)\n4. Use a dedicated job scheduler (Bull, Agenda) with Redis backing\n5. Add idempotency to job execution\n6. Check if job is already running before starting\n7. Use Kubernetes CronJob (runs as separate pod)\n8. Log job execution with timestamps for debugging")

add("Fix Email HTML Rendering in Outlook", "HTML email looks broken in Microsoft Outlook:\n\n[describe the rendering issue]\n\nFix by:\n1. Use tables for layout (not div/flexbox/grid)\n2. Inline all CSS styles (no <style> block for Outlook)\n3. Use MSO conditional comments: <!--[if mso]><![endif]-->\n4. Avoid CSS shorthand (use margin-top, not margin)\n5. Set fixed widths on table cells\n6. Use bgcolor attribute instead of CSS background\n7. VML for background images in Outlook\n8. Test with Litmus or Email on Acid\n9. Keep total email width under 600px")

with open("prompts.json", "w", encoding="utf-8") as f:
    json.dump({"prompts": prompts}, f, ensure_ascii=False, indent=2)

bugfix = [p for p in prompts if p["category"] == "bugfix"]
total = len(prompts)
print(f"Total prompts: {total}")
print(f"Bugfix prompts: {len(bugfix)}")
print()
print("Bugfix breakdown:")
print(f"  Original: 50")
print(f"  New additions: {len(bugfix) - 50}")
print(f"  Total bugfix: {len(bugfix)}")
